### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**
Add text

### CODE REVIEW

**Comment by GodGun968** [comment]
Oh, this is toooo much (。>︿<)_θ. I may not be able to finish the translation , but I will try my best to translate it.

**Comment by khazoda** [comment]
That's no problem at all, thank you so very much for what you've contributed already!

**Review by khazoda — APPROVED** [review]

**Comment by GodGun968** [comment]
Some things are not so easy to translate, so I may revise them many times
I'm going to take a break from updating translations tomorrow because I have some things I have to work out. But I will submit 
new translations a few times every half a month or a month
If you add any new text during this period, please submit it to my repository at the same time (maybe github will do this for me?)
In any case, please let me know if there are any changes, because this is not going to be done overnight.
Please don't merge this, unless necessary, until I finish it

**Comment by khazoda** [comment]
> Some things are not so easy to translate, so I may revise them many times I'm going to take a break from updating translations tomorrow because I have some things I have to work out. But I will submit new translations a few times every half a month or a month If you add any new text during this period, please submit it to my repository at the same time (maybe github will do this for me?) In any case, please let me know if there are any changes, because this is not going to be done overnight. Please don't merge this, unless necessary, until I finish it

Thank you so much, if you have some questions about harder to translate names (I know I've created some nonsensical names for some plushies like Shrump, Octoplushable etc.) please let me know. For the most part those can be translated into whatever they are most like, for example Shrump -> Mushroom, Octoplushable -> Plushable Octopus. There's no rush of course, thank you so much for your contributions so far!

**Comment by GodGun968** [comment]
Okay, but if you can, please tell me the best meaning of all the names

**Comment by khazoda** [comment]
> Okay, but if you can, please tell me the best meaning of all the names

Thank you for your hard work. I hope this list can help - if you have any questions about any of the names please ask 😊

```
Rattiam          - Rat
Triceratops      - Type of dinosaur
Whelpling        - Baby dragon
Velociraptor     - Type of dinosaur
Rupert           - The name of a cat, perhaps just translate this as cat
Dragon           - Fire breathing mythological creature
Wizard           - Could be translated to any magic wielding name e.g. Sorcerer, Mage, Magus etc.
Goblin           - Fantasy creature that is small, green, often angry etc.
Beaux            - The name of a dog, perhaps just translate this as dog
Big Tater        - Big Potato
Big Irritater    - Similar to Big Potato, but Irritater is a combination of the words irritated and potato (in-case that helps)
Otter            - Name of animal
Shrump           - Mushroom
Octoplushable    - Octopus
Snail            - Name of animal
Whale            - Name of animal
Orangutan        - Name of animal
Goldfish         - Name of animal
Trater           - Similarly to Irritater, this is a combination of the words Traitor and Potato
Conductor        - Like a train conductor, it's the name of the job
Capybara         - Name of animal
Animatronic      - Could be translated as robot/automaton maybe?
Moobloom         - This is the scrapped mob from the 2020 mob vote, it probably had a chinese name too
Froge            - Frog
Owl              - Name of animal
Hampter          - Hamster (Name of animal)
Dormouse         - Name of animal
Sea Bunny        - Name of animal (also called Jorunna parva)
Statuette        - Small statue
Mammoth          - Name of animal
Tiger            - Name of animal
Walrus           - Name of animal


```

**Comment by GodGun968** [comment]
Thx, I will update them again in a few days.

**Comment by GodGun968** [comment]
I'm very busy recently. If you are in a hurry, you can merge it. zh_cn.json has been translated. Please wait for the rest### .

**Comment by khazoda** [comment]
Many thanks GodGun! I will merge the PR if I put out a new release before further contributions.

**Pull request merged**
